"""
volatility/surface_pca.py
Principal Component Analysis of implied-volatility surface dynamics.

The implied vol surface σ(k, T) moves every day.  We ask: what are the
dominant *directions* of that motion?

Method
------
1. Build a panel of daily vol surfaces  {σᵢ(k, T)}  where i indexes time.
2. Represent each surface as a vector (flattening the (k, T) grid).
3. Compute daily changes  Δσᵢ = σᵢ − σᵢ₋₁.
4. Perform PCA on the matrix of changes.

The first three PCs typically explain > 90% of variance and correspond to
interpretable "modes":
  PC1 — parallel shift  (overall level moves up/down)
  PC2 — tilt / slope    (short vs long term, or put vs call wing)
  PC3 — curvature / smile  (wings vs ATM)

This decomposition is used in practice to:
  • Hedge the vol surface with a small number of instruments.
  • Identify which part of the surface is being shocked.
  • Detect unusual surface moves (residual = surface − PC1+PC2+PC3 projection).

Data source (two modes)
-----------------------
real  : requires pre-computed historical IV grids (Bloomberg / OptionMetrics).
        YFinance does NOT provide historical option chains so this path uses
        synthetic surfaces generated by Heston with time-varying parameters,
        mimicking what real calibrated surfaces look like.
synthetic : Heston-generated panel — suitable for the CV project and for
            demonstrating understanding of the methodology.

References
----------
Cont & da Fonseca (2002) "Dynamics of Implied Volatility Surfaces", Quant Finance.
Fengler, Härdle & Villa (2003) "The Dynamics of Implied Volatilities", Review of Finance.
"""

from __future__ import annotations

import numpy as np
from dataclasses import dataclass
from typing import Optional


# ── Result containers ─────────────────────────────────────────────────────────

@dataclass
class PCAResult:
    """
    PCA of vol-surface daily changes.

    Attributes
    ----------
    k_grid        : log-moneyness grid
    T_grid        : maturity grid
    explained_var : fraction of variance explained by each PC
    components    : PC loadings reshaped to (n_PC, n_T, n_k)
    scores        : daily PC scores  (n_days, n_PC)
    mean_surface  : mean vol surface  σ̄(k, T)  (n_T, n_k)
    eigenvalues   : raw eigenvalues
    """
    k_grid: np.ndarray
    T_grid: np.ndarray
    explained_var: np.ndarray        # (n_PC,)
    components: np.ndarray           # (n_PC, n_T, n_k)
    scores: np.ndarray               # (n_days, n_PC)
    mean_surface: np.ndarray         # (n_T, n_k)
    eigenvalues: np.ndarray          # (n_PC,)
    cumulative_var: np.ndarray       # (n_PC,)

    @property
    def n_components(self) -> int:
        return len(self.explained_var)

    def reconstruct(self, n_components: int, day: int = -1) -> np.ndarray:
        """
        Reconstruct a single day's surface using the top-n_components PCs.
        Returns array shaped (n_T, n_k).
        """
        n = min(n_components, self.n_components)
        n_T, n_k = self.components.shape[1], self.components.shape[2]
        flat = (self.mean_surface.ravel()
                + sum(self.scores[day, i] * self.components[i].ravel()
                      for i in range(n)))
        return flat.reshape(n_T, n_k)

    def summary(self) -> str:
        lines = ["PCA of Implied Volatility Surface Dynamics"]
        for i, (ev, cv) in enumerate(
            zip(self.explained_var, self.cumulative_var)
        ):
            lines.append(
                f"  PC{i+1}: {ev*100:5.1f}% variance  "
                f"(cumulative {cv*100:5.1f}%)  "
                f"eigenvalue={self.eigenvalues[i]:.4f}"
            )
        return "\n".join(lines)

    def component_name(self, i: int) -> str:
        """Heuristic label for the first three PCs."""
        labels = {0: "Level (parallel shift)",
                  1: "Slope (term structure tilt)",
                  2: "Curvature (smile / convexity)"}
        return labels.get(i, f"PC{i+1}")


# ── PCA engine ────────────────────────────────────────────────────────────────

class VolSurfacePCA:
    """
    PCA of vol surface daily changes.

    Parameters
    ----------
    k_grid : log-moneyness grid for the surface representation
    T_grid : maturity grid (years)
    n_components : number of PCs to retain
    """

    def __init__(
        self,
        k_grid: Optional[np.ndarray] = None,
        T_grid: Optional[np.ndarray] = None,
        n_components: int = 5,
    ):
        self.k_grid      = k_grid if k_grid is not None else np.linspace(-0.30, 0.30, 25)
        self.T_grid      = T_grid if T_grid is not None else np.array([0.08, 0.25, 0.5, 1.0, 2.0])
        self.n_components = n_components

    def fit(self, surfaces: np.ndarray) -> PCAResult:
        """
        Fit PCA to a panel of vol surfaces.

        Parameters
        ----------
        surfaces : array of shape (n_days, n_T, n_k)
                   Each entry is σ_impl(k, T) for one day.

        Returns
        -------
        PCAResult
        """
        n_days, n_T, n_k = surfaces.shape
        flat = surfaces.reshape(n_days, n_T * n_k)    # (n_days, n_features)

        # Daily changes
        changes      = np.diff(flat, axis=0)          # (n_days-1, n_features)
        mean_change  = changes.mean(axis=0)
        centered     = changes - mean_change

        # SVD (more numerically stable than eigen-decomposition of cov matrix)
        U, S, Vt = np.linalg.svd(centered, full_matrices=False)
        # Vt rows are eigenvectors of the covariance matrix (up to 1/(n-1) scaling)

        eigenvalues   = S ** 2 / (len(changes) - 1)
        explained_var = eigenvalues / eigenvalues.sum()
        n_pc          = min(self.n_components, len(S))

        components = Vt[:n_pc].reshape(n_pc, n_T, n_k)
        scores     = centered @ Vt[:n_pc].T           # (n_days-1, n_pc)

        return PCAResult(
            k_grid        = self.k_grid,
            T_grid        = self.T_grid,
            explained_var = explained_var[:n_pc],
            components    = components,
            scores        = scores,
            mean_surface  = flat.mean(axis=0).reshape(n_T, n_k),
            eigenvalues   = eigenvalues[:n_pc],
            cumulative_var= np.cumsum(explained_var[:n_pc]),
        )

    def fit_synthetic(
        self,
        n_days: int = 252,
        seed: int = 42,
        vol_of_vol: float = 0.15,
        mean_atm_iv: float = 0.20,
        skew_mean: float = -0.10,
    ) -> PCAResult:
        """
        Fit PCA on a synthetic panel of SSVI-generated surfaces.

        Simulates n_days of daily surface 'moves' by perturbing SSVI parameters
        as mean-reverting processes, representative of real SPX surface dynamics.
        """
        from ml.ssvi import SSVIParams

        rng = np.random.default_rng(seed)
        n_T = len(self.T_grid)
        n_k = len(self.k_grid)

        surfaces = np.zeros((n_days, n_T, n_k))

        # Time-varying SSVI parameters (mean-reverting random walks)
        # rho: skew parameter — mean-reverts around -0.7 for SPX
        # eta: vol-of-vol level
        # gamma: power-law decay
        rho_t   = -0.70
        eta_t   =  0.90
        gamma_t =  0.35

        atm_iv_t = mean_atm_iv

        for d in range(n_days):
            # Small mean-reverting perturbations
            rho_t   += 0.10 * (-0.70 - rho_t) + rng.normal(0, 0.02)
            eta_t   += 0.15 * (0.90 - eta_t)  + rng.normal(0, 0.05)
            gamma_t += 0.15 * (0.35 - gamma_t) + rng.normal(0, 0.02)
            atm_iv_t += rng.normal(0, vol_of_vol / np.sqrt(252))

            # Clip to valid ranges
            rho_t   = np.clip(rho_t,   -0.99, -0.01)
            eta_t   = np.clip(eta_t,    0.10,  5.00)
            gamma_t = np.clip(gamma_t,  0.05,  0.49)
            atm_iv_t = np.clip(atm_iv_t, 0.05, 1.00)

            ssvi = SSVIParams(rho=rho_t, eta=eta_t, gamma=gamma_t)

            for i, T in enumerate(self.T_grid):
                theta = atm_iv_t ** 2 * T
                w     = ssvi.total_var(self.k_grid, theta)
                surfaces[d, i] = np.sqrt(np.maximum(w / T, 0))

        return self.fit(surfaces)


# ── Convenience function ──────────────────────────────────────────────────────

def run_pca(n_days: int = 252, n_components: int = 5, seed: int = 42) -> PCAResult:
    """
    Quick synthetic PCA — zero setup required.

    Generates n_days of realistic SSVI-based SPX-like surfaces and returns
    the fitted PCA.  Use .summary() and .components to inspect results.
    """
    engine = VolSurfacePCA(n_components=n_components)
    return engine.fit_synthetic(n_days=n_days, seed=seed)
